
try {
    TryTest.method1();
}
catch(e:Exception) {
    System.println(e.message);
    System.println("CATCH EXCEPTION");
}

